// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrialExam;

namespace TrialExam.Migrations
{
    [DbContext(typeof(SpaceTransporterContext))]
    partial class SpaceTransporterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrialExam.Models.Planet", b =>
                {
                    b.Property<long>("PlanetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<long>("Population");

                    b.HasKey("PlanetId");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("TrialExam.Models.Spaceship", b =>
                {
                    b.Property<long>("SpaceshipId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Capacity");

                    b.Property<long>("CurrentPassengers");

                    b.Property<string>("Location");

                    b.Property<long>("PlanetId");

                    b.HasKey("SpaceshipId");

                    b.HasIndex("PlanetId")
                        .IsUnique();

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("TrialExam.Models.Spaceship", b =>
                {
                    b.HasOne("TrialExam.Models.Planet", "Planets")
                        .WithOne("Spaceship")
                        .HasForeignKey("TrialExam.Models.Spaceship", "PlanetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
