// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseApp.Models;

namespace WarehouseApp.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    [Migration("20181218092302_ReverseEngineerModels")]
    partial class ReverseEngineerModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WarehouseApp.Models.BasketItem", b =>
                {
                    b.Property<long>("BasketItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("BasketId");

                    b.Property<long?>("GoodId");

                    b.Property<int>("Quantity");

                    b.HasKey("BasketItemId");

                    b.HasIndex("BasketId");

                    b.HasIndex("GoodId");

                    b.ToTable("BasketItem");
                });

            modelBuilder.Entity("WarehouseApp.Models.Baskets", b =>
                {
                    b.Property<long>("BasketId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('0001-01-01T00:00:00.0000000')");

                    b.HasKey("BasketId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("WarehouseApp.Models.Goods", b =>
                {
                    b.Property<long>("GoodId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Stock");

                    b.HasKey("GoodId");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("WarehouseApp.Models.OrderHistory", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName");

                    b.Property<DateTime>("OrderedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('0001-01-01T00:00:00.0000000')");

                    b.HasKey("OrderId");

                    b.ToTable("OrderHistory");
                });

            modelBuilder.Entity("WarehouseApp.Models.OrderItem", b =>
                {
                    b.Property<long>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("GoodId");

                    b.Property<long?>("OrderId");

                    b.Property<int>("Quantity");

                    b.HasKey("OrderItemId");

                    b.HasIndex("GoodId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("WarehouseApp.Models.BasketItem", b =>
                {
                    b.HasOne("WarehouseApp.Models.Baskets", "Basket")
                        .WithMany("BasketItem")
                        .HasForeignKey("BasketId");

                    b.HasOne("WarehouseApp.Models.Goods", "Good")
                        .WithMany("BasketItem")
                        .HasForeignKey("GoodId");
                });

            modelBuilder.Entity("WarehouseApp.Models.OrderItem", b =>
                {
                    b.HasOne("WarehouseApp.Models.Goods", "Good")
                        .WithMany("OrderItem")
                        .HasForeignKey("GoodId");

                    b.HasOne("WarehouseApp.Models.OrderHistory", "Order")
                        .WithMany("OrderItem")
                        .HasForeignKey("OrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
